project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.ipynb"
  resources:
    - "*.ipynb"

website:
  title: "Pratique du calcul scientifique"
  navbar:
    left:
      - href: poly.qmd
        text: Polycopi√©
      - href: cours.qmd
        text: Cours
      - href: notebooks.qmd
        text: Notebooks
      - href: exam.qmd
        text: Examen
      - href: archives.qmd
        text: Archives
      - href: liens.qmd
        text: Liens utiles
      - about.qmd

editor:
    render-on-save: true

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
